//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastroUsuario
    {
        public int cadastroUsuario_id { get; set; }
        public string cadastroUsuario_user { get; set; }
        public string cadastroUsuario_senha { get; set; }
        public string cadastroUsuario_nome { get; set; }
        public Nullable<bool> cadastroUsuario_ativo { get; set; }
    }
}
