//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrinho
    {
        public int carrinho_id { get; set; }
        public Nullable<System.DateTime> carrinho_dataCadastro { get; set; }
        public Nullable<int> cliente_id { get; set; }
        public Nullable<decimal> carrinho_total { get; set; }
    }
}
