//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int pedido_id { get; set; }
        public Nullable<decimal> pedido_valor { get; set; }
        public Nullable<int> carrinhoItens_id { get; set; }
        public Nullable<System.DateTime> pedido_dataCadastro { get; set; }
    }
}
