//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidoItens
    {
        public int pedidoItens_id { get; set; }
        public Nullable<int> pedidoItens_pedido_id { get; set; }
        public Nullable<decimal> pedidoItens_valor_total { get; set; }
        public Nullable<decimal> pedidoItens_valorUnidade { get; set; }
        public Nullable<int> pedidoItens_quantidade { get; set; }
        public Nullable<int> pedidoItens_produto_id { get; set; }
        public Nullable<System.DateTime> pedidoItens_dataCadastro { get; set; }
    }
}
