//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class produto
    {
        public int produto_id { get; set; }
        public string produto_nome { get; set; }
        public string produto_desc { get; set; }
        public Nullable<bool> produto_ativo { get; set; }
        public Nullable<decimal> produto_preco { get; set; }
        public Nullable<decimal> produto_precoPromo { get; set; }
    }
}
